<a href="https://colab.research.google.com/github/ClemAppleby/ClemAppleby.github.io/blob/main/Tensorflow_Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##FCC TensorFlow 2 Course

---




In [15]:
import tensorflow as tf

<h1>Module 1 Notes - High-Level Overview</h2>

1. Three main types of ML: Supervised, Unsupervised, Reinforcement.
2. Supervised learning is appropriate when we have both labels and features.
3. Unsupervised learning is a appropriate when we have only features. Think clustering algorithms etc.
4. Reinforcement learning is appropriate when we have neither known features nor known labels. Think agents, environments, and rewards etc.


### Module 2 Notes - Intro to Tensorflow

  1. For this course we will use Tensorflow to implement the following:

*   Image Classification
*   Data Clustering
*   Regression
*   Reinforcement Learning
*   NLP







<h2>Importing Tensorflow</h2>






In [3]:
import numpy as np
import pandas as pd

##Tensors

"A tensor is a generalisation of vectors and matrices to potentially higher dimensions. Internally, TensorFlow represents tensors as n-dimensional arrays of base datatypes" https://www.tensorflow.org/guide/tensor

Tensors are the main objects that are passed around and manipulated throughout the program. Each tensor represents a partially defined computation that will eventually provide a value. TensorFlow programs work by building a graph of Tensor objects that detail how tensors are related. Running different parts of the graph allow results to be generated.

Each tensor has a data type and a shape. The shape represents the dimension of the data.

## Creating Tensors
<h5>Below is an example of how to create some different tensors:</h5>
[link text](https://)



In [5]:
string = tf.Variable('this is a string', tf.string)
number = tf.Variable(324, tf.int16)
floating = tf.Variable(3.567, tf.float64)


<h4>Rank/Degree/Shape of Tensors</h4>

Another word for rank is degree. These terms simply mean the number of dimensions involved in the tensor. The above tensor has rank 0 (scalar).

The shape of a given tensor is the name given to the number of elements in each dimension (degree) of said tensor.

In [6]:
rank1_tensor = tf.Variable(['teset', 'Ok', 'Kriss'], tf.string)
rank2_tensor = tf.Variable([['test', 'Ok'], ['test', 'yes']], tf.string)
#To determine the rank/degree of a given tensor the following code can be run:
tf.rank(rank2_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

# Shape of Tensors

The shape of a tensor is the amount of elements that exist in each degree (dimension) of the tensor.

To determine the shape of a tensor we use the shape function attribute:

In [7]:
rank2_tensor.shape

TensorShape([2, 2])

The shape of a given tensor is the product of the sizes of all its shapes. There are often many shapes that have the same number of elements, making it convient to be able to change the shape of a tensor.

For example, a rank 1 tensor with 6 elements could have the same number of elements of a rank 2 tensor with 3 elements in each dimension.

The format for the shape of a tensor is [x, y, z] where x is the number of outer lists; y is the number of inner lists; and z is the number of elements in each inner list.

The example below shows how to alter the shape of a tensor:

In [8]:
tensor1 = tf.ones([1,2,3]) #tf.ones() creates a shape [1,2,3] tensor full of ones.
tensor2 = tf.reshape(tensor1, [2,3,1]) # reshape existing date to shape [2,3,1] Note that the product of the elements is the same for both shapes.
tensor3 = tf.reshape(tensor2, [3, -1]) # -1 tells the tensor to calculate the size of the dimension in that place
                                       # this will reshape the tensor to [3,2]

Taking a look at the above tensors:

In [9]:
print(tensor1)
print(tensor2)
print(tensor3)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


<h4>Types of tensors</h4>

The most common types of tensors are:

*   Variable
*   Constant
*   Placeholder
*   SparseTensor

With the exception of 'variable' type tensors, all of these tensors are immutable.






## Evaluating Tensors

There will be various times wherein we want to evaluate a tensor to get its value. Since tensors represent a partially complete computation we will sometimes need to run a session to evaluate a tensor.

There are many ways to do this, but the simplest is illustrated in the code snippet below:

In [13]:
with tf.Session() as sess: # creates a session using the default graph
  tensor1.eval() # tensor will of course be the name of your tensor

AttributeError: module 'tensorflow' has no attribute 'Session'

In the code above the tensor variable that was stored in the default graph was evaluated. The default graph holds all operations not specified to any other graph. It is possible to create custom graphs.

In [22]:
t = tf.zeros([5,5,5,5])
t = tf.reshape(t, [125, -1])
print(t)

tf.Tensor(
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]

# Module Three